name: pull request

on:
  pull_request:
    branches: [ "master" ]
    types: [ review_requested ]
  push: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Runs a single command using the runners shell
    - name: extract pull number
      run:   echo ::set-output name=PULL_NUMBER::$(echo "$GITHUB_REF" | awk -F / '{print $3}')
      shell: bash
      id: extract
