name: self

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: ${{ secrets.CI }}
    steps:


 steps:

    - name: 'Cleanup build folder'
      run: |
        ls -la ./
        rm -rf ./* || true
        rm -rf ./.??* || true
        ls -la ./

    - uses: actions/checkout@v3
